import { mkdir,copyFile,cp,writeFile,rm } from 'node:fs/promises';
import { resolve } from 'node:path';
const out=resolve('../anteprima-jsx');
await mkdir(out+'/src',{recursive:true});await mkdir(out+'/public',{recursive:true});
await copyFile('src/components/Portfolio.jsx',out+'/src/Portfolio.jsx');
await copyFile('src/components/SplineScene.jsx',out+'/src/SplineScene.jsx');
await copyFile('src/components/OpeningSequence.jsx',out+'/src/OpeningSequence.jsx');
await copyFile('src/styles/portfolio.css',out+'/src/portfolio.css');
await cp('src/assets/fonts',out+'/assets/fonts',{recursive:true});
await cp('licenses',out+'/licenses',{recursive:true});
await copyFile('dist/preview-data.json',out+'/src/projects.json');
const generatedAssets=resolve(out,'public/_astro');
if(!generatedAssets.startsWith(out+'/')&&!generatedAssets.startsWith(out+'\\'))throw new Error('Invalid output path');
await rm(generatedAssets,{recursive:true,force:true});
await cp('dist/_astro',generatedAssets,{recursive:true});
await copyFile('public/favicon.svg',out+'/public/favicon.svg');
await writeFile(out+'/src/main.jsx',`import React from 'react';
import {createRoot} from 'react-dom/client';
import './portfolio.css';
import Portfolio from './Portfolio.jsx';
import projects from './projects.json';
createRoot(document.getElementById('root')).render(<Portfolio projects={projects} standalone/>);
`);
await writeFile(out+'/index.html',`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.svg"><title>Marco Braga — JSX preview</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`);
await writeFile(out+'/package.json',JSON.stringify({name:'marco-braga-jsx-preview',version:'1.0.0',private:true,type:'module',packageManager:'pnpm@10.17.1',scripts:{dev:'vite --host 127.0.0.1',build:'vite build',preview:'vite preview --host 127.0.0.1'},dependencies:{'@splinetool/runtime':'2.0.55',react:'19.3.0','react-dom':'19.3.0',vite:'^6.4.0'}},null,2));
await writeFile(out+'/.gitignore','node_modules/\ndist/\n');
console.log('JSX preview exported to '+out);

await writeFile(out+'/vite.config.js',"import {defineConfig} from 'vite';\nexport default defineConfig({esbuild:{jsx:'automatic'}});\n");
